name: eventide
description: "Ticketat is a vibrant, multi-functional platform revolutionizing event experiences in Mauritania, seamlessly connecting buyers, organizers, and sponsors through secure QR ticketing, smart analytics, and personalized recommendations."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  qr_flutter: ^4.0.0
  mobile_scanner: ^7.0.0
  shared_preferences: ^2.0.0
  provider: ^6.0.0
  intl: 0.20.2
  crypto: ^3.0.0
  share_plus: ^12.0.0
  file_picker: '>=8.1.2'
  firebase_core: ^4.2.0
  cloud_firestore: '>=5.5.0'
  firebase_auth: '>=5.3.3'
  firebase_storage: ^13.0.0
  google_sign_in: '>=6.2.1'
  url_launcher: ^6.0.0
  path_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/main_logo.png
  remove_alpha_ios: true
